<?php namespace JF;
/**

Copyright 2018 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-eea930
Date:    2018-06-19 13:07:38
Version: v2.1.3
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-eea930",
    "email": {
        "to": "eva@wikimedia.de",
        "cc": "",
        "bcc": "",
        "subject": "EVA ausgef\u00fcllt",
        "template": "",
        "sendmail_from": "jquery.form@aol.com"
    },
    "admin": {
        "users": "admin:35e51",
        "dataDelivery": "emailAndFile",
        "save2dbExample": true
    },
    "thankyou": {
        "url": "",
        "message": "",
        "seconds": "10"
    },
    "autoResponse": {
        "includeAttachments": true,
        "subject": "",
        "template": ""
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "mailgun",
    "smtp": {
        "host": "smtp.aol.com",
        "user": "jquery.form@aol.com",
        "password": "MailerTest2016",
        "port": "587",
        "security": "tls"
    },
    "mailgun": {
        "domain": "mg.jquery-form.com",
        "apiKey": "key-1fee8dabcdf62e1b78ef1c57bf553d6d",
        "fromEmail": "mailgun@jquery-form.com",
        "fromName": "JQuery Form"
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [],
    "fields": [
        {
            "label": "Page Navigation",
            "field_type": "page_navigation",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "navigation": {
                    "style": "steps",
                    "showNumber": true,
                    "isButtonPrev": false,
                    "titles": [
                        {
                            "id": "f11",
                            "title": "Angaben zur Person"
                        },
                        {
                            "id": "f21",
                            "title": "Angaben zum neuen Arbeitsverh\u00e4ltnis"
                        },
                        {
                            "id": "f32",
                            "title": "IT-relevante Angaben"
                        },
                        {
                            "id": "f0",
                            "title": "Office-relevante Angaben"
                        }
                    ]
                }
            },
            "id": "f12",
            "cid": "c75"
        },
        {
            "label": "Vorname der Person",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": [],
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "placeholder": "Vorname",
                "mask": {
                    "pattern": ""
                }
            },
            "id": "f6",
            "cid": "c42"
        },
        {
            "label": "Nachname der Person",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": [],
                "placeholder": "Nachname",
                "mask": {
                    "pattern": ""
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f5",
            "cid": "c32"
        },
        {
            "label": "E-Mail-Adresse",
            "field_type": "email",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "sender": false,
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": false
                    }
                },
                "mainDescription": "\u00dcblicherweise setzen wir die E-Mail-Adresse nach dem Schema \"rufname.nachname@wikimedia.de\" zusammen. Bitte kl\u00e4re im Vorfeld, ob beispielsweise Stephanie \"Steffi\" als Rufname hei\u00dfen soll.",
                "placeholder": "E-Mail-Adresse"
            },
            "id": "f7",
            "cid": "c49"
        },
        {
            "label": "Bereich",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Programme",
                        "checked": false
                    },
                    {
                        "label": "Softwareentwicklung",
                        "checked": false
                    },
                    {
                        "label": "Kommunikation und Partnerschaften",
                        "checked": false
                    },
                    {
                        "label": "Vorstand, Vorstandsreferate\/-team",
                        "checked": false
                    },
                    {
                        "label": "Central",
                        "checked": false
                    }
                ],
                "presetJson": "",
                "mainDescription": "Gib hier bitte den neuen Bereich an.",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f9",
            "cid": "c60"
        },
        {
            "label": "Team",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": [],
                "mainDescription": "Falls m\u00f6glich, gib bitte das Team an, wo die Person eingestellt werden soll, z.B. bei Central: Event oder bei Softwareentwicklung: Community Communications.",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f10",
            "cid": "c65"
        },
        {
            "label": "Angaben zur Person",
            "field_type": "page_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "page": {
                    "title": "Angaben zur Person",
                    "labelPrev": "< Back",
                    "labelNext": "Next",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}",
                    "disabled": false
                }
            },
            "id": "f11",
            "cid": "c70"
        },
        {
            "label": "Datum erster Tag des neuen Arbeitsverh\u00e4ltnis",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "glyphicon glyphicon-th",
                    "rightText": ""
                },
                "date": {
                    "daysOfWeekDisabled": {
                        "d0": true,
                        "d6": true
                    },
                    "minViewMode": "0",
                    "weekStart": "1",
                    "startView": "0"
                },
                "validators": {
                    "compareTo": {
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f14",
            "cid": "c85"
        },
        {
            "label": "Erster Tag der pers\u00f6nlichen Anwesenheit",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "glyphicon glyphicon-th",
                    "rightText": ""
                },
                "date": {
                    "daysOfWeekDisabled": {
                        "d0": true,
                        "d6": true,
                        "d4": false
                    },
                    "startView": "0",
                    "minViewMode": "0",
                    "weekStart": "1"
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f15",
            "cid": "c90"
        },
        {
            "label": "Stellenbezeichnung, deutsch",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": []
            },
            "id": "f16",
            "cid": "c96"
        },
        {
            "label": "Stellenbezeichnung, englisch",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": []
            },
            "id": "f17",
            "cid": "c101"
        },
        {
            "label": "Kommunikationsprofil der Person",
            "field_type": "checkboxes",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Leitungsfunktion (z. B. Bereichs-\/Teamleitung)",
                        "checked": false,
                        "value": "leitung"
                    },
                    {
                        "label": "Vereinskontakte (MAs, die eigenverantwortlich mit Anspruchsgruppen des Vereins kommunizieren)",
                        "checked": false,
                        "value": "vereinskontakte"
                    },
                    {
                        "label": "Wikikontakte (MAs, die verantwortliche Bezugspersonen f\u00fcr Community-Aktive sind)",
                        "checked": false,
                        "value": "wikikontakte"
                    },
                    {
                        "label": "kein Kommunikationsprofil n\u00f6tig",
                        "checked": false,
                        "value": "keinprofil"
                    }
                ],
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)"
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)"
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "presetJson": "",
                "hidden": false,
                "mainDescription": "<a href=\"https:\/\/docs.google.com\/document\/d\/1vyrkbU6nU-EiL-I-r8UPJvCF2nLRZXa_9fdQkVXx3f0\/edit#\">Kommunikationsprofile (Google Drive)<\/a>"
            },
            "id": "f18",
            "cid": "c106",
            "labelHide": false
        },
        {
            "label": "Sitzplatz",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Sitzplatz: (Eingabe n\u00f6tig)",
                        "checked": false,
                        "value": "#input"
                    },
                    {
                        "label": "remote, kein fester Arbeitsplatz in der Gesch\u00e4ftsstelle",
                        "checked": false,
                        "value": "remote"
                    }
                ],
                "presetJson": "",
                "mainDescription": "Bitte beschreibe kurz, wo die Person sitzen soll: Raum, gegen\u00fcber oder neben Kolleg*in, oder ob sie remote arbeiten soll. Arbeitet die Person haupts\u00e4chlich remote, ist der Bereich\/Team selbst verantwortlich, einen Sitzplatz f\u00fcr diese Person zu organisieren, wenn sie mal in der Gesch\u00e4ftsstelle ist.",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f20",
            "cid": "c117"
        },
        {
            "label": "Angaben zum neuen Arbeitsverh\u00e4ltnis",
            "field_type": "page_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "page": {
                    "title": "Angaben zum neuen Arbeitsverh\u00e4ltnis",
                    "labelPrev": "< Back",
                    "labelNext": "Next",
                    "showPageNumnber": true,
                    "pageNumberText": "{page} \/ {total}",
                    "disabled": false
                }
            },
            "id": "f21",
            "cid": "c127"
        },
        {
            "label": "Arbeitsrechner",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Laptop, 14, unser Standardger\u00e4t",
                        "checked": true,
                        "value": "L14"
                    },
                    {
                        "label": "Laptop, 12,5\", gut geeignet f\u00fcr Vielreisende",
                        "checked": false,
                        "value": "L12"
                    }
                ],
                "presetJson": "",
                "mainDescription": "<a href=\"https:\/\/wiki.wikimedia.de\/wiki\/IT\/Standardkonfiguration_der_WMDE_Rechner_(Hardware)\">Standardger\u00e4te WMDE (GS-Wiki)<\/a>",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f22",
            "cid": "c132"
        },
        {
            "label": "Betriebssystem",
            "field_type": "checkboxes",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Ubuntu",
                        "checked": true,
                        "value": "linux"
                    },
                    {
                        "label": "Windows",
                        "checked": false,
                        "value": "windows"
                    },
                    {
                        "label": "selbst installiert (kein Support durch interne IT)",
                        "checked": false,
                        "value": "unsupported"
                    }
                ],
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)"
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)"
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "presetJson": "",
                "mainDescription": "Standard ist Ubuntu."
            },
            "id": "f23",
            "cid": "c140"
        },
        {
            "label": "Zus\u00e4tzlicher Bildschirm",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "ja, es wird ein weiterer Bildschirm ben\u00f6tigt",
                        "checked": false,
                        "value": "ja"
                    },
                    {
                        "label": "nein",
                        "checked": false,
                        "value": "nein"
                    }
                ],
                "presetJson": "",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "mainDescription": "Jeder Arbeitsplatz wird standardm\u00e4\u00dfig mit einem Bildschirm ausgestattet."
            },
            "id": "f24",
            "cid": "c147"
        },
        {
            "label": "Mobiltelefon",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Bitte ausw\u00e4hlen -",
                        "value": "#novalue",
                        "checked": true
                    },
                    {
                        "label": "kein Mobiltelefon ben\u00f6tigt",
                        "checked": false,
                        "value": "0"
                    },
                    {
                        "label": "einfaches Ger\u00e4t f\u00fcr Erreichbarkeit",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "Smartphone, einzel-SIM",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "Smartphone, dual-SIM",
                        "value": "3",
                        "checked": false
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "presetJson": "",
                "multiple": false,
                "mainDescription": "Neue Telefone haben derzeit immer Dual-SIM. Einzel-SIM-Ger\u00e4te sind Restbest\u00e4nde. <a href=\"https:\/\/wiki.wikimedia.de\/wiki\/IT\/Standardkonfiguration_der_WMDE_Rechner_(Hardware)#Mobiltelefonie\">Mobiltelefone (GS-Wiki)<\/a>"
            },
            "id": "f25",
            "cid": "c152"
        },
        {
            "label": "Mobilfunkvertrag",
            "field_type": "checkboxes",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Telefonievertrag",
                        "checked": false,
                        "value": "erstsim"
                    },
                    {
                        "label": "Zweit-SIM (f\u00fcr Laptop, Tablet u.\u00e4.)",
                        "checked": false,
                        "value": "zweitsim"
                    }
                ],
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)"
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)"
                    }
                },
                "presetJson": "",
                "mainDescription": "Bei Bedarf sind mehrere Antworten m\u00f6glich."
            },
            "id": "f26",
            "cid": "c159"
        },
        {
            "label": "Festnetztelefon",
            "field_type": "checkboxes",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "DECT-Festnetztelefon",
                        "checked": false
                    }
                ],
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)"
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)"
                    }
                },
                "presetJson": ""
            },
            "id": "f27",
            "cid": "c169"
        },
        {
            "label": "Weitere Anforderungen an Hard- und Software",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "mainDescription": "Bitte kl\u00e4rt im Vorfeld mit der IT, ob der Bedarf so oder anders erf\u00fcllt werden kann."
            },
            "id": "f28",
            "cid": "c174"
        },
        {
            "label": "Zug\u00e4nge",
            "field_type": "checkboxes",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "OTRS (WMF)",
                        "checked": false,
                        "value": "otrswmf"
                    },
                    {
                        "label": "OTRS (Fundraising)",
                        "checked": false,
                        "value": "otrswmfg"
                    },
                    {
                        "label": "CiviCRM (allgemein)",
                        "checked": false,
                        "value": "civicrm"
                    },
                    {
                        "label": "CiviCRM (Mailings, impliziert allgemein)",
                        "checked": null,
                        "value": "civimailings"
                    },
                    {
                        "label": "Fundraising Netzlaufwerk",
                        "checked": null,
                        "value": "wmfgshare"
                    },
                    {
                        "label": "www.wikimedia.de Bearbeitungsrechte",
                        "checked": null,
                        "value": "homepageeditor"
                    },
                    {
                        "label": "blog.wikimedia.de Bearbeitungsrechte",
                        "checked": null,
                        "value": "blogeditor"
                    },
                    {
                        "label": "forum.wikimedia.de",
                        "checked": null,
                        "value": "forum"
                    }
                ],
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)"
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)"
                    }
                },
                "presetJson": "",
                "mainDescription": "Zug\u00e4nge werden standardm\u00e4\u00dfig gelegt f\u00fcr GS-Wiki, Redmine (user) und TicTac. OTRS (WMF) kann erst angelegt werden, wenn die Person ihre Arbeit aufgenommen hat, kann also nicht am ersten Arbeitstag bereitstehen."
            },
            "id": "f29",
            "cid": "c179"
        },
        {
            "label": "Mailingliste",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": [],
                "mainDescription": "Mailinglisten bitte kommasepariert eingeben. \"kollegium@\" ist Standard."
            },
            "id": "f31",
            "cid": "c189"
        },
        {
            "label": "IT-relevante Angaben",
            "field_type": "page_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "page": {
                    "title": "IT-relevante Angaben",
                    "labelPrev": "< Back",
                    "labelNext": "Next",
                    "showPageNumnber": true,
                    "pageNumberText": "{page} \/ {total}",
                    "disabled": false
                }
            },
            "id": "f32",
            "cid": "c194"
        },
        {
            "label": "BVG-Ticket",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Bitte ausw\u00e4hlen -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "kein Ticket",
                        "checked": false,
                        "value": "keines"
                    },
                    {
                        "label": "AB (Eigenanteil durch MA 14,25\u20ac)",
                        "checked": false,
                        "value": "bvgab"
                    },
                    {
                        "label": "ABC (Eigenanteil durch MA 32,88\u20ac)",
                        "checked": false,
                        "value": "bvgabc"
                    },
                    {
                        "label": "Abrechnung \u00fcber Kostenerstattungsformular (z.B. f\u00fcr kurzfristige Anstellungen wie Praktikant*innen)",
                        "value": "bvgkef",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "presetJson": "",
                "multiple": false,
                "mainDescription": "Info: Bis zum 10. eines Vormonats muss das BVG-Ticket bestellt werden (Vorstand muss unterschreiben), damit die neue Person zum Anfang des neuen Monats das BVG Ticket erh\u00e4lt (Bsp.: Bestellung bis 10.06. = BVG-Ticket ab 01.07.). Sollte die Bestellung zeitlich nicht m\u00f6glich sein, k\u00f6nnen die Kosten f\u00fcr den \u00dcberbr\u00fcckungszeitraum nach Absprache zwischen F\u00fchrungskraft und der neuen Person erstattet werden. Das Office-Team h\u00e4ndigt der Person das BVG-Ticket nach Quittierung aus. Bei kurzzeitigen Arbeitsverh\u00e4ltnissen empfiehlt sich die Variante 4; sprecht dazu bitte die Personalabteilung an. <a href=\"https:\/\/wiki.wikimedia.de\/wiki\/BVG_Abos\">weitere Informationen (GS-Wiki)<\/a>"
            },
            "id": "f33",
            "cid": "c199"
        },
        {
            "label": "falls BVG-Ticket, \u2026",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "glyphicon glyphicon-th",
                    "rightText": ""
                },
                "date": {
                    "weekStart": "1",
                    "startView": "0",
                    "minViewMode": "0"
                },
                "mainDescription": "\u2026 ab wann?"
            },
            "id": "f34",
            "cid": "c204"
        },
        {
            "label": "Transponderzug\u00e4nge",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "allgemeiner Transponder",
                        "checked": false,
                        "value": "allgemein"
                    },
                    {
                        "label": "spezielle Schlie\u00dfungen: (Eingabe ben\u00f6tigt)",
                        "checked": false,
                        "value": "#input"
                    },
                    {
                        "label": "kein Transponder ben\u00f6tigt",
                        "checked": false,
                        "value": "keintransponder"
                    }
                ],
                "presetJson": "",
                "mainDescription": "Bitte spezielle Schlie\u00dfungen angeben falls ben\u00f6tigt."
            },
            "id": "f35",
            "cid": "c211"
        },
        {
            "label": "Postfach beim Empfang ben\u00f6tigt?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "ja",
                        "checked": false,
                        "value": "ja"
                    },
                    {
                        "label": "nein",
                        "checked": false,
                        "value": "nein"
                    }
                ],
                "presetJson": "",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f36",
            "cid": "c216"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Office-relevante Angaben",
                    "labelPrev": "< Back",
                    "showPageNumnber": true,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "licenseKey": "",
    "lang": {
        "language": "de"
    }
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class