var config = {
  'id' : 'WMDE/WebApp EVA',
  'maintainer': 'masin.al-dujaili@wikimedia.de',
  'debug': true,
  'projekte': {
    'EVA': {
/*      'spreadsheet': '15_o6U0yTbv4xrdd_Wk5qbsOsIQx4LiyWEIkrT7ubPPQ',
      'responses': 'Formularantworten',
      'form': '1FIVlHgxu9LLzh3jsqoHb4AQB0N5XZ1fPZLR0hw_C1Vs',
      'filter': '1uSP-alBZLQxl7kHmrzEcszuKTkVn3fMi2RJgXjfjnpU',
      'directory': 'EVA'*/
      'spreadsheet': '1wRV60Jwz2semi73pwJ-wlFPvBpb83J2fHzxkpgKWkZI'
    },
  },
  'stakeholder': {
    '20180301': {
      'Rohdaten': [],
      'IT': ['meldung', 'vorname', 'nachname', 'bereichNeu', 'team', 'ersterTag', 'anwesenheit', 'stelleDE', 'stelleEN', 'sitzplatz',
             'rechner', 'os', 'monitore', 'handy', 'handyvertrag', 'dect', 'weitereHW', 'optionaleSW', 'zugaenge', 'listen',
             'wann', 'veraenderungLaptop', 'veraenderungHandy', 'veraenderungDect', 'sitzplatzNeu',
             'letzterTag', 'autoreply', 'gdocs', 'konten', 'rueckkehr', 'abwesenheit', 'abwesenheitLaptop', 'abwesenheitHandy'],
      'Office': ['meldung', 'vorname', 'nachname', 'bereichNeu', 'team', 'ersterTag', 'anwesenheit', 'stelleDE', 'stelleEN', 'sitzplatz',
                 'handyvertrag', 'dect', 'bvg', 'bvgDatum', 'bahncard', 'transponder', 'postfach', 'wann',
                 'veraenderungBVG', 'veraenderungBahncard', 'veraenderungHandy', 'veraenderungTransponder', 'veraenderungDect', 'sitzplatzNeu',
                 'letzterTag', 'rueckkehr', 'abwesenheit', 'abwesenheitBVG', 'abwesenheitBahncard', 'abwesenheitTransponder' ],
      'Vorstand': ['meldung', 'vorname', 'nachname', 'bereichNeu', 'team', 'ersterTag', 'anwesenheit', 'stelleDE', 'stelleEN',
                   'kommProfil', 'sitzplatz', 'grundVeraenderung', 'wann', 'kommProfilNeu', 'sitzplatzNeu', 'grundAustritt',
                   'letzterTag', 'rueckkehr', 'abwesenheit'],
      'Personal': ['meldung', 'vorname', 'nachname', 'bereichNeu', 'team', 'ersterTag', 'anwesenheit', 'stelleDE', 'stelleEN', 'sitzplatz',
                   'bvg', 'grundVeraenderung', 'wann', 'veraenderungBVG', 'veraenderungBahncard', 'sitzplatzNeu',
                   'grundAustritt', 'letzterTag', 'rueckkehr', 'abwesenheit', 'abwesenheitBVG', 'abwesenheitBahncard'],
      'IF': ['meldung', 'vorname', 'nachname', 'bereichNeu', 'team', 'ersterTag', 'anwesenheit', 'stelleDE', 'stelleEN',
             'wann', 'letzterTag', 'rueckkehr', 'abwesenheit'],
      'Kommunikation': ['meldung', 'vorname', 'nachname', 'bereichNeu', 'team', 'ersterTag', 'anwesenheit', 'stelleDE', 'stelleEN',
                        'kommProfil', 'wann', 'kommProfilNeu', 'letzterTag', 'rueckkehr', 'abwesenheit'],
      'Betriebsrat': ['meldung', 'vorname', 'nachname', 'bereichNeu', 'team', 'ersterTag', 'anwesenheit', 'stelleDE', 'stelleEN',
                      'wann', 'letzterTag', 'rueckkehr', 'abwesenheit']
    }
  },
  stakeholder_matrix: '1uSP-alBZLQxl7kHmrzEcszuKTkVn3fMi2RJgXjfjnpU'
};

var meldung = 'Personeller Vorgang',
    vorname = 'Vorname der Person',
    nachname = 'Nachname der Person',
    bereichNeu = 'Bereich / Team',
    team = 'Team',
    ersterTag = 'Datum erster Tag des neuen Anstellungsverhältnis',
    anwesenheit = 'Erster Tag der persönlichen Anwesenheit',
    stelleDE = 'Stellenbezeichnung, deutsch',
    stelleEN = 'Stellenbezeichnung, englisch',
    kommProfil = 'Kommunikationsprofil der Person',
    sitzplatz = 'Sitzplatz',
    rechner = 'Arbeitsrechner',
    os = 'Betriebssystem',
    monitore = 'Zusätzlicher Bildschirm',
    handy = 'Mobiltelefon',
    handyvertrag = 'Mobilfunkvertrag',
    dect = 'Festnetztelefon',
    weitereHW = 'Weitere Anforderungen an Hard- und Software',
    optionaleSW = 'optionale, kostenpflichtige Software',
    zugaenge = 'Zugänge',
    listen = 'Mailingliste',
    bvg = 'BVG-Ticket',
    bvgDatum = 'falls BVG-Ticket, …',
    bahncard = 'on Hold (BahnCard)',
    transponder = 'Transponderzugänge',
    postfach = 'Postfach beim Empfang benötigt?',
    grundVeraenderung = 'Grund der Veränderung',
    wann = 'Ab wann gilt die Veränderung?',
    kommProfilNeu = 'Kommunikationsprofil der Person nach Änderung der Stelle',
    veraenderungBVG = 'Verwendung von Arbeitsausstattung nach Änderung der Stelle [BVG-Ticket]',
    veraenderungBahncard = 'Verwendung von Arbeitsausstattung nach Änderung der Stelle [BahnCard]',
    veraenderungLaptop = 'Verwendung von Arbeitsausstattung nach Änderung der Stelle [Laptop]',
    veraenderungHandy = 'Verwendung von Arbeitsausstattung nach Änderung der Stelle [Handy]',
    veraenderungTransponder = 'Verwendung von Arbeitsausstattung nach Änderung der Stelle [Transponder]',
    veraenderungDect = 'Verwendung von Arbeitsausstattung nach Änderung der Stelle [DECT-Telefon]',
    sitzplatzNeu = 'Sitzplatz nach Änderung der Stelle',
    grundAustritt = 'Grund des Austritts',
    letzterTag = 'Datum letzter Tag des laufenden Vertrages',
    autoreply = 'Adresse in Autoreply für Mails',
    gdocs = 'Eigentümer für Docs in Google Drive',
    konten = 'Zugänge/Accounts',
    rueckkehr = 'Voraussichtliche Rückkehr auf den Arbeitsplatz',
    abwesenheit = 'Datum letzter Tag der persönlichen Anwesenheit',
    abwesenheitBVG = 'Verwendung von Arbeitsausstattung während Abwesenheit [BVG-Ticket]',
    abwesenheitBahncard = 'Verwendung von Arbeitsausstattung während Abwesenheit [BahnCard]',
    abwesenheitLaptop = 'Verwendung von Arbeitsausstattung während Abwesenheit [Laptop]',
    abwesenheitHandy = 'Verwendung von Arbeitsausstattung während Abwesenheit [Handy]',
    abwesenheitTransponder = 'Verwendung von Arbeitsausstattung während Abwesenheit [Transponder]';